### ISSUE TITLE
Library dependency System.Drawing.Common prevents compilations for Linux

### ISSUE THREAD

**Issue by jpetzke** [jnccd/socha-client-csharp#1]
For recent versions of .NET (6.0), the code won't compile anymore.
After removing the dependency and the code that uses it (png creation of the board), it works.

![grafik](https://user-images.githubusercontent.com/54205956/144623748-7ca068e1-ca20-4ec5-967d-e79e0358df85.png)

**Comment by jnccd** [comment]
Sorry that I didnt respond to this anymore in the last season,
this season I checked if the project works on ubuntu so the new client should have less problems on other platforms.

However from the error message it looks like it was the Colored Console Printing / Getting the Console Title that caused the issue.

**Comment by jpetzke** [comment]
I solved it by simply removing the dependency and changed the related code
